-- ==========================================================================
--  hosts.lua — SSH/SFTP Host Launcher for WezTerm
--
--  Reads ~/.ssh/config and provides a fuzzy picker to connect
--  via SSH or SFTP in a new tab. Tracks connections for tab titles.
--
--  For both SSH and SFTP, offers a per-host remote directory history: picks
--  from recently used dirs, lets you type a new one, or defaults to the
--  remote home. History persists to ~/.config/wezterm/remote_dirs.lua
--  (not in repo) as `{ host = {…} }` — SSH and SFTP share the same list
--  per host. Old per-proto files are auto-migrated on load.
--
--  Keybinding: CMD+SHIFT+H
--  Usage: require("hosts").apply_to_config(config)
-- ==========================================================================

local wezterm = require("wezterm")
local state = require("state")
local M = {}

-- ── Remote dir history (ssh + sftp) ──────────────────────────────────────

local MAX_REMOTE_DIR_HISTORY = 15

local function remote_dirs_path()
  return (os.getenv("HOME") or "") .. "/.config/wezterm/remote_dirs.lua"
end

-- Load history, bypassing Lua's require cache so edits appear immediately.
-- Shape: `{ [host] = { dir, dir, ... } }`. Old per-proto files shaped
-- `{ ssh = {host = {...}}, sftp = {host = {...}} }` are auto-migrated by
-- merging both protos' lists per host (dedupe, ssh order first).
local function load_remote_dirs()
  package.loaded["remote_dirs"] = nil
  local ok, t = pcall(require, "remote_dirs")
  if not ok or type(t) ~= "table" then return {} end

  if type(t.ssh) == "table" or type(t.sftp) == "table" then
    local flat = {}
    for _, proto in ipairs({ "ssh", "sftp" }) do
      local by_host = t[proto]
      if type(by_host) == "table" then
        for host, list in pairs(by_host) do
          if type(list) == "table" then
            flat[host] = flat[host] or {}
            local seen = {}
            for _, d in ipairs(flat[host]) do seen[d] = true end
            for _, d in ipairs(list) do
              if not seen[d] then
                table.insert(flat[host], d)
                seen[d] = true
              end
            end
          end
        end
      end
    end
    return flat
  end
  return t
end

local function write_remote_dirs(all)
  local f = io.open(remote_dirs_path(), "w")
  if not f then return false end
  f:write("-- Auto-generated by hosts.lua — remote directory history per host.\n")
  f:write("-- Most-recently-used first. Shared between SSH and SFTP. Safe to edit.\n")
  f:write("return {\n")
  local hosts = {}
  for h in pairs(all) do table.insert(hosts, h) end
  table.sort(hosts)
  for _, host in ipairs(hosts) do
    local list = all[host]
    if type(list) == "table" and #list > 0 then
      f:write(string.format("  [%q] = {\n", host))
      for _, d in ipairs(list) do
        f:write(string.format("    %q,\n", d))
      end
      f:write("  },\n")
    end
  end
  f:write("}\n")
  f:close()
  return true
end

local function get_remote_history(host)
  local all = load_remote_dirs()
  return all[host] or {}
end

-- Move `dir` to the front of host's history, dedupe, cap at MAX.
local function record_remote_dir(host, dir)
  if not dir or #dir == 0 then return end
  local all = load_remote_dirs()
  local list = all[host] or {}
  local new_list = { dir }
  for _, d in ipairs(list) do
    if d ~= dir and #new_list < MAX_REMOTE_DIR_HISTORY then
      table.insert(new_list, d)
    end
  end
  all[host] = new_list
  write_remote_dirs(all)
end

-- Drop `dir` from host's history. No-op if missing.
local function forget_remote_dir(host, dir)
  if not dir or #dir == 0 then return end
  local all = load_remote_dirs()
  local list = all[host]
  if not list then return end
  local new_list = {}
  for _, d in ipairs(list) do
    if d ~= dir then table.insert(new_list, d) end
  end
  all[host] = new_list
  write_remote_dirs(all)
end

-- Shell-quote for safe `zsh -c` — wraps in single quotes, escapes embedded ones.
local function sh_quote(s)
  return "'" .. s:gsub("'", "'\\''") .. "'"
end

-- ── Parse SSH Config ─────────────────────────────────────────────────────

local function parse_ssh_hosts()
  local home = os.getenv("HOME") or ""
  local f = io.open(home .. "/.ssh/config", "r")
  if not f then return {} end

  local hosts = {}
  local current = nil

  for line in f:lines() do
    local trimmed = line:match("^%s*(.-)%s*$")
    if trimmed and #trimmed > 0 and not trimmed:match("^#") then
      local host_part = trimmed:match("^[Hh]ost%s+(.+)$")
      local is_host = host_part and not trimmed:match("^%s*[Hh]ost[A-Za-z]")
      if is_host then
        for alias in host_part:gmatch("%S+") do
          if not alias:match("[%*%?]") then
            current = { name = alias, hostname = nil, user = nil, port = nil }
            table.insert(hosts, current)
          end
        end
      end
      if current then
        local hn = trimmed:match("^%s*[Hh]ost[Nn]ame%s+(%S+)")
        if hn then current.hostname = hn end
        local u = trimmed:match("^%s*[Uu]ser%s+(%S+)")
        if u then current.user = u end
        local p = trimmed:match("^%s*[Pp]ort%s+(%d+)")
        if p then current.port = p end
      end
    end
  end
  f:close()
  return hosts
end

-- ── Spawner (new tab / split right / split down) ────────────────────────

-- `spawn_args` is the argv table passed directly to execvp — no shell wrapper.
-- The dir (if any) is already encoded in argv by `build_spawn_args`.
--
-- `open_mode` is "tab" | "right" | "bottom". We used to dispatch a separate
-- InputSelector to ask this, but chaining a third InputSelector (host → dir
-- → open-where) silently drops the deepest callback in wezterm. So the
-- where-to-open choice is baked into the dir picker entries instead, and
-- open_connection just executes the choice without its own picker.
local function open_connection(window, pane, proto, name, open_mode, spawn_args)
  local function track(new_pane)
    if not new_pane then return end
    local pid_ok, pid = pcall(function() return new_pane:pane_id() end)
    if pid_ok and pid then
      state.pane_connections[tostring(pid)] = { proto = proto, host = name }
    end
  end

  if open_mode == "tab" then
    local ok, _tab, new_pane = pcall(function()
      return window:mux_window():spawn_tab({ args = spawn_args })
    end)
    if ok then track(new_pane) end
  else
    local direction = open_mode == "right" and "Right" or "Bottom"
    local ok, new_pane = pcall(function()
      return pane:split({ direction = direction, args = spawn_args })
    end)
    if ok then track(new_pane) end
  end
end

-- ── Remote-dir picker (ssh + sftp) ───────────────────────────────────────

-- Build the argv to spawn for `proto` + host. Both protos encode the dir in
-- argv so the remote is already `cd`'d into it before the prompt appears.
--
-- SSH: argv = { "ssh", "-t", host, "cd '<dir>' 2>/dev/null; exec ${SHELL:-/bin/bash} -l" }
--   `-t` forces a PTY, the outer single quotes keep the command one argv
--   entry, the inner single quotes are escaped so the remote shell sees
--   `cd 'dir'` literally, and `exec ${SHELL:-/bin/bash} -l` replaces the
--   wrapper with a login shell so it owns the PTY. Without a dir we fall
--   back to plain interactive ssh.
-- SFTP: argv = { "sftp", "host:<dir>" } — sftp(1) cds into the path before
--   the prompt when the destination is given as `host:path`.
local function build_spawn_args(proto, name, dir)
  if proto == "sftp" then
    if dir and #dir > 0 then
      return { "sftp", name .. ":" .. dir }
    end
    return { "sftp", name }
  end
  if dir and #dir > 0 then
    local remote_cmd = "cd " .. sh_quote(dir) .. " 2>/dev/null; exec ${SHELL:-/bin/bash} -l"
    return { "ssh", "-t", name, remote_cmd }
  end
  return { "ssh", name }
end

-- Show the dir picker for this (proto, host), then spawn directly.
--
-- Each dir entry is expanded into 3 choices (new tab / split right / split
-- down) so the where-to-open decision is made in the same picker. We can't
-- dispatch a third InputSelector from this callback — wezterm silently drops
-- callbacks on the deepest picker when three are chained.
local function remote_dir_picker(window, pane, proto, name)
  local history = get_remote_history(name)

  -- Base dir entries: { id, label }. `id` is either "__default__",
  -- "__type__", or "dir:<path>".
  local base_dirs = {
    { id = "__default__", label = "🏠  Default (remote home)" },
    { id = "__type__",    label = "⌨   Type remote directory…" },
  }
  for _, d in ipairs(history) do
    table.insert(base_dirs, { id = "dir:" .. d, label = "📁  " .. d })
  end

  local modes = {
    { key = "tab",    suffix = "  ▸  New Tab" },
    { key = "right",  suffix = "  ▸  Split Right" },
    { key = "bottom", suffix = "  ▸  Split Down" },
  }

  local choices = {}
  for _, b in ipairs(base_dirs) do
    for _, m in ipairs(modes) do
      table.insert(choices, {
        id = m.key .. "|" .. b.id,
        label = b.label .. m.suffix,
      })
    end
    -- History entries also get a Remove variant. Default/Type don't.
    if b.id:match("^dir:") then
      table.insert(choices, {
        id = "remove|" .. b.id,
        label = b.label .. "  ▸  🗑  Remove from history",
      })
    end
  end

  window:perform_action(
    wezterm.action.InputSelector({
      title = "  " .. proto:upper() .. " → " .. name .. "  (dir + where to open)",
      choices = choices,
      fuzzy = true,
      fuzzy_description = "Type to filter dirs / where:",
      action = wezterm.action_callback(function(w, p, composite_id)
        if not composite_id then return end
        local open_mode, dir_id = composite_id:match("^(%w+)|(.+)$")
        if not open_mode or not dir_id then return end

        if open_mode == "remove" then
          local dir = dir_id:match("^dir:(.+)$")
          if dir then
            forget_remote_dir(name, dir)
            pcall(function()
              w:toast_notification("WezTerm",
                "Removed '" .. dir .. "' from " .. name .. " history",
                nil, 3000)
            end)
          end
          return
        end

        local function finalize(dir)
          if dir and #dir > 0 then
            record_remote_dir(name, dir)
          end
          open_connection(w, p, proto, name, open_mode, build_spawn_args(proto, name, dir))
        end

        if dir_id == "__default__" then
          finalize(nil)
        elseif dir_id == "__type__" then
          w:perform_action(
            wezterm.action.PromptInputLine({
              description = wezterm.format({
                { Attribute = { Intensity = "Bold" } },
                { Foreground = { Color = "#a6e3a1" } },
                { Text = "  " .. proto:upper() .. " " .. name .. " — remote directory to cd into:" },
              }),
              action = wezterm.action_callback(function(w2, _, line)
                if not line or #line == 0 then return end
                finalize(line)
              end),
            }),
            p
          )
        else
          finalize(dir_id:match("^dir:(.+)$"))
        end
      end),
    }),
    pane
  )
end

-- ── Host Launcher ────────────────────────────────────────────────────────

local function host_launcher(window, pane)
  local hosts = parse_ssh_hosts()
  if #hosts == 0 then
    local tmp = os.tmpname()
    local f = io.open(tmp, "w")
    if f then
      f:write("No hosts found in ~/.ssh/config\n\nPress q to close.\n")
      f:close()
    end
    window:perform_action(
      wezterm.action.SpawnCommandInNewTab({
        args = { "/bin/zsh", "-c", string.format("less '%s'; rm -f '%s'", tmp, tmp) },
      }),
      pane
    )
    return
  end

  -- Build choices: each host gets an SSH and SFTP entry
  local choices = {}
  for _, h in ipairs(hosts) do
    local display_info = h.hostname and ("  →  " .. h.hostname) or ""
    if h.port and h.port ~= "22" then
      display_info = display_info .. ":" .. h.port
    end

    table.insert(choices, {
      id = "ssh:" .. h.name,
      label = "SSH   " .. h.name .. display_info,
    })
    table.insert(choices, {
      id = "sftp:" .. h.name,
      label = "SFTP  " .. h.name .. display_info,
    })
  end

  window:perform_action(
    wezterm.action.InputSelector({
      title = "  Host Launcher — SSH / SFTP",
      choices = choices,
      fuzzy = true,
      fuzzy_description = "Type to search hosts:",
      action = wezterm.action_callback(function(inner_window, inner_pane, id, _)
        if not id then return end
        local proto, name = id:match("^(%w+):(.+)$")
        if not proto then return end
        remote_dir_picker(inner_window, inner_pane, proto, name)
      end),
    }),
    pane
  )
end

-- ── Apply to Config ──────────────────────────────────────────────────────

function M.apply_to_config(config)
  config.keys = config.keys or {}

  -- CMD+SHIFT+H → Host Launcher (SSH/SFTP picker from ~/.ssh/config)
  table.insert(config.keys, {
    key = "h",
    mods = "CMD|SHIFT",
    action = wezterm.action_callback(function(window, pane)
      local ok, err = pcall(host_launcher, window, pane)
      if not ok then
        wezterm.log_error("Host launcher error: " .. tostring(err))
      end
    end),
  })
end

return M
